import Head from 'next/head'
import Image from 'next/image'
import ParticleField from "react-particles-webgl";
import styles from '../styles/Home.module.css'

export default function Home() {

  const config = {
    showCube: false,
    dimension: '2D',
    velocity: 2,
    boundaryType: 'bounce',
    antialias: false,
    direction: {
      xMin: -1,
      xMax: 1,
      yMin: -1,
      yMax: 1,
      zMin: -1,
      zMax: 1
    },
    lines: {
      colorMode: 'rainbow',
      color: '#351CCB',
      transparency: 0.9,
      limitConnections: true,
      maxConnections: 20,
      minDistance: 110,
      visible: true
    },
    particles: {
      colorMode: 'rainbow',
      color: '#3FB568',
      transparency: 0.9,
      shape: 'circle',
      boundingBox: 'canvas',
      count: 330,
      minSize: 20,
      maxSize: 50,
      visible: true
    },
    cameraControls: {
      enabled: false,
      enableDamping: true,
      dampingFactor: 0.2,
      enableZoom: true,
      autoRotate: false,
      autoRotateSpeed: 0.3,
      resetCameraFlag: true
    },
    limitConnections: true
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.bg}>
        <ParticleField config={config} />
      </div>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href='https://renakhys.duckdns.org'>Renakhys.duckdns.org</a>
        </h1>

        <p className={styles.description}>
          Test server hosting
        </p>

      </main>

    </div>
  )
}
